services:
  - type: web
    name: frontend-lbs
    env: node
    buildCommand: npm ci && npm run build:prod && cp serve.json dist/lbs/serve.json
    startCommand: npx serve dist/lbs -c dist/lbs/serve.json -s -l $PORT
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: "https://backend-api-lbs.onrender.com"
      - key: USE_MOCK_DATA
        value: "false"
